# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 351458cf4303f0f40de0ad276eb6bc927dc17c7f5c744e2d66706eb9f65cd040be327addb05c9d70924757b9b7cefa0dcbdb660ad379a962c892aeb736484fd8

test:
  secret_key_base: a8a0074c0bf6c1c95428e3f6a7be15167f23f31b0eda797832127dd4f729689689c53ae8a4e31acef814a9e3951c2124d0d584ad65c722f0c58826a661d90561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
